### ISSUE TITLE
TUIO 2.0

### ISSUE THREAD

**Issue by mkalten** [nosuchtim/TUIO3D_Sensel#1]
Hi @nosuchtim, I am the developer of the TUIO protocol, and I recently got back working on TUIO 2.0, which may be relevant for the Sensel Morph device, since it also supports the necessary pressure attributes for example. I am thinking about getting such a device, since it would be a great example platform taking advantage of the new TUIO2 capabilities. 
http://www.tuio.org/?tuio20
There is already some example code here, which could be integrated into your app instead of TUIO11 https://github.com/mkalten/TUIO20_CPP
Since I'd be also interested in testing the device, are you in any way affiliated to Sensel Morph?

**Comment by nosuchtim** [comment]
Hi Martin,

The Morph is indeed fantastic.

I've used TUIO heavily for many years, thank you for developing it.  I've given the 2.0 version a look, thanks for the pointer to the example code.  I love TUIO for cursor information, and I found it natural to use the 'z' value in a 25D profile to represent the Morph's pressure.  When I needed (years ago) to send lots and lots of data (e.g. the contours of many large objects, 60fps), I ended up doing it with shared memory in order to make it faster.  This TUIO3D_Sensel app supports either TUIO or the shared memory interface.  I'm very content with TUIO, so my motivation to add TUIO2 support is low, but perhaps someone can use this app as a starting point for TUIO2 support.

I'm not affiliated with Sensel, I'm just a very grateful customer.

     ...Tim...

**Comment by mkalten** [comment]
Thanks for the clarification @nosuchtim !
Although it's quite easy to extend or circumvent missing TUIO 1.1 features through custom OSC messages, or the "alternative" use of attributes, TUIO 2.0 actually intends to represent these new features such as Pressure and Blob Contour in a proper way. While I understand that these modifications work fine for personal use, this unfortunately also breaks the compatibility with standard TUIO layers.

Since I am planning to get one of those Sensel Morph devices, I will probably have a look at porting your code to the new TUIO 2.0 protocol generation, since its seems to be a nice use case for its extended features.  

I'll keep you posted ... Martin.K
